#version 450
#extension GL_EXT_debug_printf : enable

layout(std430, set=0, binding=0) buffer inA { int test1[]; };
layout(std430, set=1, binding=0) buffer outB { int test2[]; };

layout (local_size_x = 1) in;
int size = 10;		
int old_size =10;



void remove_element(int value){
	bool found =false;	
	int indexToRemove = -1;

	for(int i=0;i<size;i++){
		if(test1[i]==value){
			found = true;
			indexToRemove = i;
		}
	}
	if(found){
		for (int i = indexToRemove; i < size-1; i++) { 
    		test1[i] = test1[i + 1];
		}
		test1[size-1] =-1;
	}
	size = size-1;

}

void add_element(int value){
	bool found = false;
	for(int i=0;i<old_size;i++){
		if(test1[i] == -1){
			test1[i] = value;
			size++;
			break;
		}
	}
}

void main(){ 
	const uint index = gl_GlobalInvocationID.x;

	for(int i=0;i<old_size;i++){
		test2[i]=test1[i];
	}
	remove_element(1);
	add_element(100);
	remove_element(2);
	remove_element(3);
	add_element(99);
	add_element(101);
	remove_element(101);
	remove_element(5);
	remove_element(7);

	//for(int i=0;i<size;i++){
	//	test2[i] = test1[i];
	//}


	//test2[index]=test1[index]*test1[index];
}